# -*- coding: utf-8 -*-
"""Exponential Distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJYLQUUGEqZHSjhYUG82Dqy_SH_UxMBp

Problem: Suppose the failure rate λ(lambda) of a battery is 0.02 failures per hour. What is the probability that the battery fails within the next 50 hours? Conversely, what is the probability that the battery will not fail within the next 50 hours?
"""

import numpy as np

# Set required variables for calculation
lmbd = 0.02
x = 50
e = np.e

# Finds the probability of success using the exponential distribution formula
cdf_expon = e ** (-lmbd * x)
cdf_expon_percent = np.round(cdf_expon * 100, decimals=2)
print(f"The probability that the battery will survive after {x} hours is {cdf_expon_percent}%.")

# Finds the probability of failure using the probability of success
final_probability = 100 - cdf_expon_percent
print(f"The probability that the battery will not survive after {x} hours is {final_probability}%.")